# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 944401238ef9add44776a5a8b35886d111c0e072c38cf796855bcf2dee946e41fb8a0c7c2ad3fe60f545ff2cf0cc8dad72296a223c85d483e42994143eb5b296

test:
  secret_key_base: 696800e09ad51307c5f00b1fb45b4039edc45708442698bc70daeb10db6b8fea39d2cfaad30ecfb9c4d86854be72e1304baadc903e720e61fb35bf6ceb5df14c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
